# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application



on:
  repository_dispatch:
    types: [start]
    
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        python sherlock.py --timeout 1 ${{ github.event.client_payload.username }}
    - id: git_commit
      uses: zwaldowski/git-commit-action@v1
      with:
        # Directory to create commit in
       commit_message: Added new Text File # default is Automated commit
         # Name to use for commit author
       author_name: AndrewWeir421 # optional, default is GitHub Actions
         # Email to use for commit author
       author_email: andrewweir@weirtech.net # optional, default is actions@github.com
    - name: Push_Commits
      run:
        git branch -M master
        git remote add origin 'https://github.com/Sherlock-Online/Sherlock-Online.github.io'  
        git push -u origin master
    
