# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application



on:
  repository_dispatch:
    types: [start]
    

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:  
    - uses: actions/checkout@v3
      with:
          token: ${{ secrets.AUTH }}
    - name: Set up Python 3.10
      env:
          GITHUB_TOKEN: ${{ secrets.AUTH }}
        
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        cd usernames
        python /home/runner/work/Sherlock-Online.github.io/Sherlock-Online.github.io/sherlock.py --timeout 1 ${{ github.event.client_payload.username }}
        git config --global user.email "andrewwweir@weirtech.net"
        git config --global user.name "AndrewWeir421"
        git add .
        git commit -m "Added ${{ github.event.client_payload.username }}.txt"
        git push origin main
       
